### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by obtim** [mkdirlove/WI-TOOLKIT#11]
Android 11
Python 3.10.0
Root
Termux 0.101

Got this error

$ sudo python wi-toolkit.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/WI-TOOLKIT/wi-toolkit.py", line 8, in <module>
    exec(marshal.loads('c\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00@\x00\x00\x00s\xac\x00\x00\x00d\x00\x00d\x01\x00l\x00\x00Z\x00\x00d\x00\x00d\x01\x00l\x01\x00Z\x01\x00d\x00\x00d\x01\x00l\x02\x00Z\x02\x00d\x00\x00d\x02\x00l\x00\x00m\x03\x00Z\x03\x00\x01d\x00\x00d\x03\x00l\x04\x00m\x05\x00Z\x05\x00\x01d\x04\x00Z\x06\x00d\x05\x00Z\x07\x00d\x06\x00Z\x08\x00e\x00\x00j\t\x00\x83\x00\x00d\x07\x00k\x02\x00sx\x00e\x01\x00j\n\x00d\x08\x00\x83\x01\x00\x01n\x00\x00e\x00\x00j\x03\x00d\t\x00\x83\x01\x00\x01e\x07\x00GHe\x08\x00GHd\n\x00\x84\x00\x00Z\x0b\x00d\x0b\x00\x84\x00\x00Z\x0c\x00e\x0c\x00\x83\x00\x00\x01d\x01\x00S(\x0c\x00\x00\x00i\xff\xff\xff\xffN(\x01\x00\x00\x00t\x06\x00\x00\x00system(\x01\x00\x00\x00t\x05\x00\x00\x00sleeps"\x00\x00\x00\n[+] https://github.com/rmdirlove\ns\xa9\x06\x00\x00\x1b[93m               \n\xe2\x94\x8c\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x90\n\xe2\x94\x82                                                                      \xe2\x94\x82\n\xe2\x94\x82\xe2\x96\x84     \xe2\x96\x84   \xe2\x96\x80          \xe2\x96\x84\xe2\x96\x84\xe2\x96\x84\xe2\x96\x84\xe2\x96\x84\xe2\x96\x84\xe2\x96\x84               \xe2\x96\x80\xe2\x96\x80\xe2\x96\x88    \xe2\x96\x88        \xe2\x96\x80      \xe2\x96\x84   \xe2\x94\x82\n\xe2\x94\x82\xe2\x96\x88  \xe2\x96\x88  \xe2\x96\x88 \xe2\x96\x84\xe2\x96\x84\xe2\x96\x84             \xe2\x96\x88     \xe2\x96\x84\xe2\x96\x84\xe2\x96\x84    \xe2\x96\x84\xe2\x96\x84\xe2\x96\x84     \xe2\x96\x88    \xe2\x96\x88   \xe2\x96\x84  \xe2\x96\x84\xe2\x96\x84\xe2\x96\x84    \xe2\x96\x84\xe2\x96\x84\xe2\x96\x88\xe2\x96\x84\xe2\x96\x84 \xe2\x94\x82\n\xe2\x94\x82\xe2\x96\x80 \xe2\x96\x88\xe2\x96\x80\xe2\x96\x88 \xe2\x96\x88   \xe2\x96\x88             \xe2\x96\x88    \xe2\x96\x88\xe2\x96\x80 \xe2\x96\x80\xe2\x96\x88  \xe2\x96\x88\xe2\x96\x80 \xe2\x96\x80\xe2\x96\x88    \xe2\x96\x88    \xe2\x96\x88 \xe2\x96\x84\xe2\x96\x80     \xe2\x96\x88      \xe2\x96\x88   \xe2\x94\x82\n\xe2\x94\x82 \xe2\x96\x88\xe2\x96\x88 \xe2\x96\x88\xe2\x96\x88\xe2\x96\x80   \xe2\x96\x88     \xe2\x96\x80\xe2\x96\x80\xe2\x96\x80     \xe2\x96\x88    \xe2\x96\x88   \xe2\x96\x88  \xe2\x96\x88   \xe2\x96\x88    \xe2\x96\x88    \xe2\x96\x88\xe2\x96\x80\xe2\x96\x88      \xe2\x96\x88      \xe2\x96\x88   \xe2\x94\x82\n\xe2\x94\x82 \xe2\x96\x88   \xe2\x96\x88  \xe2\x96\x84\xe2\x96\x84\xe2\x96\x88\xe2\x96\x84\xe2\x96\x84           \xe2\x96\x88    \xe2\x96\x80\xe2\x96\x88\xe2\x96\x84\xe2\x96\x88\xe2\x96\x80  \xe2\x96\x80\xe2\x96\x88\xe2\x96\x84\xe2\x96\x88\xe2\x96\x80    \xe2\x96\x80\xe2\x96\x84\xe2\x96\x84  \xe2\x96\x88  \xe2\x96\x80\xe2\x96\x84  \xe2\x96\x84\xe2\x96\x84\xe2\x96\x88\xe2\x96\x84\xe2\x96\x84    \xe2\x96\x80\xe2\x96\x84\xe2\x96\x84 \xe2\x94\x82\n\xe2\x94\x82                                                                      \xe2\x94\x82\n\xe2\x94\x82              CODED BY: https://github.com/mkdirlove
\xe2\x94\x82\n\xe2\x94\x94\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x98\n\xe2\x94\x82   .::[+] GREETINGS : https://web.facebook.com/daisuke.chiba1 [+]::.  \xe2\x94\x82\n\xe2\x94\x82    .::[+] GREETINGS : https://web.facebook.com/jflorence07 [+]::.    \xe2\x94\x82\n\xe2\x94\x94\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x98                              \n       sj\x00\x00\x00\x1b[92m\n[1] WPS Attack\n[2] WPA / WPA2 Attack\n[3] Offline Bruteforce\n[4] Install & Update\n[5] Exit Tool\n    \ni\x00\x00\x00\x00s8\x00\x00\x00\x1b[1;91m\n[!] You must run this program as root. [!]\n\x1b[1;ms\x0e\x00\x00\x00clear && clearc\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00C\x00\x00\x00sN\x00\x00\x00t\x00\x00d\x01\x00\x83\x01\x00}\x00\x00|\x00\x00d\x02\x00\x19j\x01\x00\x83\x00\x00d\x03\x00k\x02\x00r,\x00t\x02\x00\x83\x00\x00\x01n\x1e\x00t\x03\x00j\x04\x00d\x04\x00\x83\x01\x00\x01t\x05\x00GHt\x06\x00GHt\x07\x00\x83\x00\x00\x01d\x00\x00S(\x05\x00\x00\x00Ns\x12\x00\x00\x00Continue [Y/n] -> i\x00\x00\x00\x00t\x01\x00\x00\x00Nt\x05\x00\x00\x00clear(\x08\x00\x00\x00t\t\x00\x00\x00raw_inputt\x05\x00\x00\x00uppert\x04\x00\x00\x00exitt\x02\x00\x00\x00osR\x00\x00\x00\x00t\x04\x00\x00\x00logot\x04\x00\x00\x00menut\x06\x00\x00\x00select(\x01\x00\x00\x00t\x03\x00\x00\x00con(\x00\x00\x00\x00(\x00\x00\x00\x00s\x0c\x00\x00\x00tahmid_rayatt\x04\x00\x00\x00quit+\x00\x00\x00s\x0e\x00\x00\x00\x00\x01\x0c\x01\x16\x01\n\x02\r\x01\x05\x01\x05\x01c\x00\x00\x00\x00\r\x00\x00\x00\x05\x00\x00\x00C\x00\x00\x00s\x1a\x02\x00\x00y\xfd\x01t\x00\x00d\x01\x00\x83\x01\x00}\x00\x00|\x00\x00d\x02\x00k\x02\x00r\xaa\x00t\x01\x00j\x02\x00d\x03\x00\x83\x01\x00\x01t\x03\x00d\x04\x00\x83\x01\x00}\x01\x00d\x05\x00j\x04\x00|\x01\x00\x83\x01\x00}\x02\x00t\x02\x00|\x02\x00\x83\x01\x00\x01d\x06\x00j\x04\x00|\x01\x00\x83\x01\x00}\x03\x00d\x07\x00GHt\x02\x00|\x03\x00\x83\x01\x00\x01d\x08\x00GHt\x03\x00d\t\x00\x83\x01\x00}\x04\x00d\n\x00GHt\x05\x00d\x0b\x00\x83\x01\x00\x01d\x0c\x00j\x04\x00|\x01\x00|\x04\x00\x83\x02\x00}\x05\x00t\x02\x00|\x05\x00\x83\x01\x00\x01nR\x01|\x00\x00d\r\x00k\x02\x00r^\x01t\x01\x00j\x02\x00d\x03\x00\x83\x01\x00\x01t\x03\x00d\x04\x00\x83\x01\x00}\x01\x00d\x05\x00j\x04\x00|\x01\x00\x83\x01\x00}\x02\x00t\x02\x00|\x02\x00\x83\x01\x00\x01d\x0e\x00j\x04\x00|\x01\x00\x83\x01\x00}\x06\x00d\x0f\x00GHt\x05\x00d\x10\x00\x83\x01\x00\x01t\x02\x00|\x06\x00\x83\x01\x00\x01d\x08\x00GHt\x03\x00d\t\x00\x83\x01\x00}\x04\x00t\x03\x00d\x11\x00\x83\x01\x00}\x07\x00t\x03\x00d\x12\x00\x83\x01\x00}\x08\
00d\x13\x00j\x04\x00|\x07\x00|\x04\x00|\x08\x00|\x01\x00\x83\x04\x00}\t\x00t\x02\x00|\t\x00\x83\x01\x00\x01n\x9e\x00|\x00\x00d\x0b\x00k\x02\x00rq\x01t\x06\x00\x01n\x8b\x00|\x00\x00d\x14\x00k\x02\x00r\xb9\x01t\x01\x00j\x02\x00d\x15\x00\x83\x01\x00\x01d\x16\x00GHt\x01\x00j\x02\x00d\x17\x00\x83\x01\x00\x01t\x01\x00j\x02\x00d\x18\x00\x83\x01\x00\x01t\x01\x00j\x02\x00d\x19\x00\x83\x01\x00\x01nC\x00|\x00\x00d\x10\x00k\x02\x00r\xfc\x01t\x03\x00d\x1a\x00\x83\x01\x00}\n\x00t\x03\x00d\x1b\x00\x83\x01\x00}\x0b\x00d\x1c\x00j\x04\x00|\x0b\x00|\n\x00\x83\x02\x00}\x0c\x00t\x02\x00|\x0c\x00\x83\x01\x00\x01n\x00\x00Wn\x16\x00\x04t\x07\x00k\n\x00r\x15\x02\x01\x01\x01d\x1d\x00GHn\x01\x00Xd\x00\x00S(\x1e\x00\x00\x00Ns\x1b\x00\x00\x00\x1b[91mmkdirlove@root:~# \x1b[0mi\x01\x00\x00\x00s\t\x00\x00\x00airmon-ngs\x16\x00\x00\x00Enter your interface: sA\x00\x00\x00ifconfig {0} down && iwconfig {0} mode monitor && ifconfig {0} ups\x0b\x00\x00\x00wash -i {0}s\x1a\x00\x00\x00\x1b[1mCtrl + C to stop. \x1b[0mt\x01\x00\x00\x00 s\x07\x00\x00\x00Bssid: s\x1e\x00\x00\x00\x1b[1mStarting WPS Attack...\x1b[0mi\x05\x00\x00\x00s\x15\x00\x00\x00reaver -i {0} -b {1} i\x02\x00\x00\x00s\x0f\x00\x00\x00airodump-ng {0}s\x19\x00\x00\x00\x1b[1mCtrl + C To Stop \x1b[0mi\x03\x00\x00\x00s\n\x00\x00\x00Channel : s\x0c\x00\x00\x00File Name : s)\x00\x00\x00airodump-ng -c {0} --bssid {1} -w {2} {3}i\x04\x00\x00\x00R\x03\x00\x00\x00s4\x00\x00\x00This tool is avilable for Unix / Linux like systems.s5\x00\x00\x00git clone https://github.com/mkdirlove/WI-TOOLKIT.gits&\x00\x00\x00cd WI-TOOLKIT && sudo bash ./update.shs\n\x00\x00\x00wi-toolkits\x0f\x00\x00\x00Wordlist path: s\x15\x00\x00\x00Enter Captured file: s\x17\x00\x00\x00aircrack-ng {0} -w {1} t\x00\x00\x00\x00(\x08\x00\x00\x00t\x05\x00\x00\x00inputR\x07\x00\x00\x00R\x00\x00\x00\x00R\x04\x00\x00\x00t\x06\x00\x00\x00formatR\x01\x00\x00\x00R\x06\x00\x00\x00t\x11\x00\x00\x00KeyboardInterrupt(\r\x00\x00\x00t\x06\x00\x00\x00choicet\t\x00\x00\x00interfacet\x05\x00\x00\x00intert\x04\x00\x00\x00washt\x05\x00\x00\x00bssidt\x06\x00\x00\x00reavert\x04\x00\x00\x00dumpt\x02\x00\x00\x00cht\x02\x00\x00\x00svt\x04\x00\x00\x00airot\x08\x00\x00\x00wordlistt\x05\x00\x00\x00save2t\x05\x00\x00\x00crack(\x00\x00\x00\x00(\x00\x00\x00\x00s\x0c\x00\x00\x00tahmid_rayatR\n\x00\x00\x005\x00\x00\x00s\\\x00\x00\x00\x00\x01\x03\x01\x0c\x01\x0c\x01\r\x01\x0c\x01\x0f\x01\n\x01\x0f\x01\x05\x01\n\x01\x05\x01\x0c\x01\x05\x01\n\x01\x12\x01\r\x01\x0c\x01\r\x01\x0c\x01\x0f\x01\n\x01\x0f\x01\x05\x01\n\x01\n\x01\x05\x01\x0c\x01\x0c\x01\x0c\x01\x18\x01\r\x01\x0c\x01\x07\x01\x0c\x01\r\x01\x05\x01\r\x01\r\x01\x10\x01\x0c\x01\x0c\x01\x0c\x01\x12\x01\x11\x01\r\x01(\r\x00\x00\x00R\x07\x00\x00\x00t\x03\x00\x00\x00syst\n\x00\x00\x00subprocessR\x00\x00\x00\x00t\x04\x00\x00\x00timeR\x01\x00\x00\x00t\x06\x00\x00\x00followR\x08\x00\x00\x00R\t\x00\x00\x00t\x07\x00\x00\x00geteuidR\x06\x00\x00\x00R\x0c\x00\x00\x00R\n\x00\x00\x00(\x00\x00\x00\x00(\x00\x00\x00\x00(\x00\x00\x00\x00s\x0c\x00\x00\x00tahmid_rayatt\x08\x00\x00\x00<module>\x02\x00\x00\x00s\x1e\x00\x00\x00\x0c\x01\x0c\x01\x0c\x01\x10\x01\x10\x04\x06\x10\x06\x08\x06\x03\x12\x01\x10\x02\r\x01\x05\x01\x05\x01\t\n\t/'))
TypeError: a bytes-like object is required, not 'str'

**Comment by sansanmhmd10** [comment]
> Android 11 Python 3.10.0 Root Termux 0.101
> 
> Punya kesalahan ini?
> 
> $ sudo python wi-toolkit.py Traceback (panggilan terakhir terakhir): File "/data/data/com.termux/files/home/WI-TOOLKIT/wi-toolkit.py", baris 8, di exec(marshal.loads('c\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00@\x00\x00\x00s\xac\x00\x00\x00d\x00\ x00d\x01\x00l\x00\x00Z\x00\x00d\x00\x00d\x01\x00l\x01\x00Z\x01\x00d\x00\x00d\x01\x00l\x02\x00Z\x02\x00d\x00\x00d\ x02\x00l\x00\x00m\x03\x00Z\x03\x00\x01d\x00\x00d\x03\x00l\x04\x00m\x05\x00Z\x05\x00\x01d\x04\x00Z\x06\x00d\x05\ x00Z\x07\x00d\x06\x00Z\x08\x00e\x00\x00j\t\x00\x83\x00\x00d\x07\x00k\x02\x00sx\x00e\x01\x00j\n\x00d\x08\x00\ x83\x01\x00\x01n\x00\x00e\x00\x00j\x03\x00d\t\x00\x83\x01\x00\x01e\x07\x00GHe\x08\x00GHd\n\x00\x84\x00\x00Z\ x0b\x00d\x0b\x00\x84\x00\x00Z\x0c\x00e\x0c\x00\x83\x00\x00\x01d\x01\x00S(\x0c\x00\x00\x00i\xff\xff\xff\xffN (\x01\x00\x00\x00t\x06\x00\x00\x00system(\x01\x00\x00\x00t\x05\x00\x00\x00sleeps"\x00\x00\x00\n[+] [https:// github.com/rmdirlove\ns\xa9\x06\x00\x00\x1b[93m](https://github.com/rmdirlove%5Cns%5Cxa9%5Cx06%5Cx00%5Cx00%5Cx1b%5B93m) \n\xe2\x94\x8c\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80 \xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2 \x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94 \x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80 \xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2 \x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94 \x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80 \xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2 \x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x90\n\xe2\x94\x82 \xe2\x94\x82\n\xe2\x94\x82\xe2\x96\x84 \xe2\x96\x84 \xe2\x96\x80 \xe2\x96\x84\ xe2\x96\x84\xe2\x96\x84\xe2\x96\x84\xe2\x96\x84\xe2\x96\x84\xe2\x96\x84 \xe2\x96\x80\xe2\x96\x80\xe2\ x96\x88 \xe2\x96\x88 \xe2\x96\x80 \xe2\x96\x84 \xe2\x94\x82\n\xe2\x94\x82\xe2\x96\x88 \xe2\x96\x88 \xe2\ x96\x88 \xe2\x96\x84\xe2\x96\x84\xe2\x96\x84 \xe2\x96\x88 \xe2\x96\x84\xe2\x96\x84\xe2\x96\x84 \xe2\x96\ x84\xe2\x96\x84\xe2\x96\x84 \xe2\x96\x88 \xe2\x96\x88 \xe2\x96\x84 \xe2\x96\x84\xe2\x96\x84\xe2\x96\x84 \ xe2\x96\x84\xe2\x96\x84\xe2\x96\x88\xe2\x96\x84\xe2\x96\x84 \xe2\x94\x82\n\xe2\x94\x82\xe2\x96\x80 \ xe2\x96\x88\xe2\x96\x80\xe2\x96\x88 \xe2\x96\x88 \xe2\x96\x88 \xe2\x96\x88\xe2\x96\x88\xe2\x96\x80 \xe2\x96\x80\xe2\x96\x88 \xe2\x96\x88\xe2\x96\x80 \xe2\x96\x80\xe2\x96\x88 \xe2 \x96\x88 \xe2\x96\x88 \xe2\x96\x84\xe2\x96\x80 \xe2\x96\x88 \xe2\x96\x88 \xe2\x94\x82\n\xe2\x94\x82 \xe2 \x96\x88\xe2\x96\x88 \xe2\x96\x88\xe2\x96\x88\xe2\x96\x80 \xe2\x96\x88 \xe2\x96\x80\xe2\x96\x80\xe2\x96 \x80 \xe2\x96\x88 \xe2\x96\x88 \xe2\x96\x88 \xe2\x96\x88 \xe2\x96\x88 \xe2\x96\x88 \xe2\x96\x88\xe2\x96\x80 \xe2\x96\x88 \xe2\x96\x88 \xe2\x96\x88 \xe2\x94\x82\n\xe2\x94\x82 \xe2\x96\x88 \xe2\x96\x88 \xe2\x96\x84 \xe2\x96\x84\xe2\x96\x88\xe2\x96\x84\xe2\x96\x84 \xe2\x96\x88 \xe2\x96\x80\xe2\x96\x88\xe2\x96\x84\xe2 \x96\x88\xe2\x96\x80 \xe2\x96\x80\xe2\x96\x88\xe2\x96\x84\xe2\x96\x88\xe2\x96\x80 \xe2\x96\x80\xe2\x96 \x84\xe2\x96\x84 \xe2\x96\x88 \xe2\x96\x80\xe2\x96\x84\xe2\x96\x84\xe2\x96\x84\xe2\x96\x88\xe2\x96\x84\xe2\x96\x84 \xe2\x96\x80\xe2\x96\x84\xe2\x96\x84 \xe2 \x94\x82\n\xe2\x94\x82 \xe2\x94\x82\n\xe2\x94\x82 DIKODEKAN OLEH:https://github.com/mkdirlove \xe2\x94\x82\n\xe2\x94\x94\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80 \xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2 \x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94 \x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80 \xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2 \x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94 \x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80 \xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2 \x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x98\n\xe2\x94\x82 .::[+] SALAM :https://web.facebook.com/daisuke.chiba1 [+]::. \xe2\x94\x82\n\xe2\x94\x82 .::[+] SALAM : https://web.facebook.com/jflorence0794\x80\xe2\x94\x98 \n sj\x00\x00\x00\x1b[92m\n[1] Serangan WPS\n[2] Serangan WPA / WPA2\n[3] Bruteforce Offline\n[4] Install & Update\n[5] Exit Tool\n \ni\x00\x00\x00\x00s8\x00\x00\x00\x1b[1;91m\n[!] Anda harus menjalankan program ini sebagai root. [!]\n\x1b[1;ms\x0e\x00\x00\x00clear && clearc\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00C\x00\x00\ x00sN\x00\x00\x00t\x00\x00d\x01\x00\x83\x01\x00}\x00\x00|\x00\x00d\x02\x00\x19j\x01\x00\x83\x00\x00d\x03\ x00k\x02\x00r,\x00t\x02\x00\x83\x00\x00\x01n\x1e\x00t\x03\x00j\x04\x00d\x04\x00\x83\x01\x00\x01t\x05\x00GHt\x06 \x00GHt\x07\x00\x83\x00\x00\x01d\x00\x00S(\x05\x00\x00\x00Ns\x12\x00\x00\x00Lanjutkan [Y/n] -> sA\x00\x00\x00ifconfig {0} down && iwconfig {0} mode monitor && ifconfig {0} ups\x0b\x00\x00\x00wash -i {0}s\x1a\x00\x00\x00\x1b[1mCtrl + C untuk berhenti. \x1b[0mt\x01\x00\x00\x00 s\x07\x00\x00\x00Bssid: s\x1e\x00\x00\x00\x1b[1mMemulai Serangan WPS...\x1b[0mi\x05\x00\x00 \x00s\x15\x00\x00\x00reaver -i {0} -b {1} i\x02\x00\x00\x00s\x0f\x00\x00\x00airodump-ng {0}s\x19\x00\x00\ x00\x1b[1mCtrl + C Untuk Menghentikan \x1b[0mi\x03\x00\x00\x00s\n\x00\x00\x00Channel : s\x0c\x00\x00\x00Nama File : s)\x00\x00\x00airodump- ng -c {0} --bssid {1} -w {2} {3}i\x04\x00\x00\x00R\x03\x00\x00\x00s4\x00\x00\x00Alat ini tersedia untuk Unix / Linux seperti system.s5\x00\x00\x00git clone https://github.com/mkdirlove/WI-TOOLKIT.gits&\x00\x00\x00cd WI-TOOLKIT && Sudo bash ./update.shs\n\x00\x00\ x00wi-toolkits\x0f\x00\x00\x00Jalur daftar kata: TypeError: diperlukan objek seperti byte, bukan 'str'

what's the solution

**Comment by Samsudin08** [comment]
Gblok pake python2

**Comment by MohamadBayz** [comment]
Same in here

**Comment by MohamadBayz** [comment]
Any solution?
