### ISSUE TITLE
How can i running as root?

### ISSUE THREAD

**Issue by Caserol23** [mkdirlove/WI-TOOLKIT#6]
Really epic fail, i'm rooted device, but it seems need to update, even "sudo" is unknown, when this is Termux, sudo is'nt yet updated...

i used "python" and "python2" is'nt working well
![Screenshot_2021-05-19-23-55-13-252_com termux](https://user-images.githubusercontent.com/16409238/118845073-0af58a80-b8fe-11eb-8ec4-aada4054eb9e.png)

**Comment by Cheesterman03** [comment]
apt update su 😍

**Comment by mkdirlove** [comment]
sudo python2 wi-toolkit.py
